### ISSUE TITLE
absent values in img_rank TSV column prevent display of image details

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_back#2]
Due to the presence of NULL instead of imgrank 0 in images DB table

**Comment by grololo06** [comment]
In logs:
```
[2020-06-09 06:17:59,902] ERROR in __init__: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./appli/project/objectdetails.py", line 73, in objectdetails
    .format(img.imgrank+1,img.file_name,width,height,minifile,miniwidth,miniheight))
```
