### ISSUE TITLE
Missing authentication leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by moi90** [ecotaxa/ecotaxa_back#34]
If I do an API request without supplying credentials, I get a 500 Internal Server Error:

```
----------- BACK-END -------------
  File "/app/main.py", line 1474, in export_object_set
    rsp = sce.run(current_user)
  File "/app/API_operations/exports/ForProject.py", line 54, in run
    _user, _project = RightsBO.user_wants(self.session, current_user_id, Action.READ, self.req.project_id)
  File "/app/BO/Rights.py", line 45, in user_wants
    assert user is not None
AssertionError

Traceback (most recent call last):
  File "download2.py", line 29, in <module>
    response.raise_for_status()
  File "/home/mschroeder/21-morphocluster-sd-extension-run/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://ecotaxa.obs-vlfr.fr/api/object_set/export
```

This should rather be a 401 Unauthorized.

**Comment by grololo06** [comment]
Indeed, a few `with RightsThrower():` have been forgotten in main.py, so some primitives auth fail with dirty message.
