### ISSUE TITLE
Project import: Validation / ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by moi90** [ecotaxa/ecotaxa_back#68]
I have a tsv file created through Pandas (in fact, pyecotaxa). It contains the column `object_annotation_category_id` which is defined to be numeric (`"[f]"`) in `py/BO/Mappings.py:28`. Therefore (and because it contains empty values), it is saved as float by Pandas.

Upon import, i get the following error:
```
Analyzing file ecotaxa_035.tsv
2023-07-10 14:34:44,736:BO.TSVFile:INFO New field object_morphocluster_label found in file ecotaxa_035.tsv -> t02
2023-07-10 14:34:44,736:BO.TSVFile:INFO New field object_id_src found in file ecotaxa_035.tsv -> t03
2023-07-10 14:34:44,738:BO.TSVFile:INFO sample: s119 acquis: uvp5_s119
2023-07-10 14:34:46,585:BO.TSVFile:INFO sample: s120 acquis: uvp5_s120
2023-07-10 14:34:49,818:BO.TSVFile:INFO sample: ctd000 acquis: uvp5_ctd000
2023-07-10 14:34:49,831:API_operations.helpers.JobService:ERROR Unexpected termination of #83002
2023-07-10 14:34:49,831:API_operations.helpers.JobService:ERROR invalid literal for int() with base 10: '92059.0'
Traceback (most recent call last):
  File "/app/API_operations/helpers/JobService.py", line 76, in run_in_background
    self.do_background()
  File "/app/API_operations/imports/Import.py", line 81, in do_background
    self.do_validate()
  File "/app/API_operations/imports/Import.py", line 122, in do_validate
    how, diag, nb_rows = self._collect_existing_and_validate(
  File "/app/API_operations/imports/Import.py", line 184, in _collect_existing_and_validate
    nb_rows = source_bundle.validate_import(
  File "/app/BO/Bundle.py", line 208, in validate_import
    total_row_count = self.validate_each_file(how, diag, report_def)
  File "/app/BO/Bundle.py", line 285, in validate_each_file
    rows_for_csv = tsv_to_validate.do_validate(how, diag)
  File "/app/BO/TSVFile.py", line 780, in do_validate
    rows_for_csv = self.validate_content(how, diag)
  File "/app/BO/TSVFile.py", line 879, in validate_content
    self.validate_line(how, diag, lig, vals_cache)
  File "/app/BO/TSVFile.py", line 1007, in validate_line
    diag.classif_id_seen.add(int(csv_val))
ValueError: invalid literal for int() with base 10: '92059.0'
```

The error is caused in the following code snippet:
```python
elif is_numeric:
    vf = to_float(csv_val)
    if vf is None:
        diag.error(
            "Invalid float value '%s' for Field '%s' in file %s."
            % (csv_val, raw_field, self.relative_name)
        )
    elif a_field == "object_annotation_category_id":
        diag.classif_id_seen.add(int(csv_val))
```

I find this implementation very weird. I would expect the `elif a_field == "object_annotation_category_id"` be on the same level of (and prior to) `elif is_numeric:`. Also, later in the actual import, `object_annotation_category_id` is seemingly allowed to be empty (`py/BO/TSVFile.py:543` in `read_fields_to_dicts`).

Because how commonly Pandas is used and because it reads columns with numeric and empty values as float (which is reasonable as the `int` type can not represent NaN), I suggest to allow float-formatted integers in this place.

Also, I get why it makes sense to do validation and the actual import in two steps. However, the process is already very slow (because `csv.DictReader` is very slow) and much time is wasted because the data is parsed twice. I think it would make sense to use pyecotaxa here, parse the data once and pass a sanitized `DataFrame` to the import step.

**Comment by grololo06** [comment]
We'll never do import in a single pass. Users have taken the habit that basically, after the validation phase, they can forget about the import and do something else with near 100% chances it will be OK.

**Comment by moi90** [comment]
> We'll never do import in a single pass. Users have taken the habit that basically, after the validation phase, they can forget about the import and do something else with near 100% chances it will be OK.

How does that relate to my error?

**Comment by grololo06** [comment]
Oops, I got lost in the text of the comment. The topic drifted a bit in the end.

**Comment by moi90** [comment]
Sorry, yes, my text is a bit all over the place...

**Comment by grololo06** [comment]
I try to shorten release cycle so hopefully in 1W from now your panda will be happy :)

**Comment by moi90** [comment]
You're great!
