### ISSUE TITLE
API: issue uploading larger files (but still less than 500 MB)

### ISSUE THREAD

**Issue by LAMaglan** [ecotaxa/ecotaxa_back#87]
From the GUI, I have tested and successful in uploading zipped files of size 230 MB (see partial screenshot):
![Screenshot from 2024-11-04 13-57-30](https://github.com/user-attachments/assets/4034afc9-b960-4e96-9326-f6da24a80a4c)

However, via the API, I am unable to import the *same* file (note: I start the project fresh with no data).
I do this with some python code, which works fine with smaller files (less than 50 MB).
For this larger file, it seems like I can still get the server-side path with `POST: /myfiles/` and take the result of that and send to `POST: /file_import/{project_id}`. This is what my python code is printing out:
```python
Server upload file path: /tmp/tmppthykknq.3121/ecotaxa_CPICS_20240905_000023_20240905_235921.zip
Starting file_import with source_path: /tmp/tmppthykknq.3121/ecotaxa_CPICS_20240905_000023_20240905_235921.zip
Import is started. See the Task section in Ecotaxa GUI for more details: {"job_id":128305,"errors":[]}
```
But, in the Ecotaxa "task" view, it says that the zip file is not a valid zip file, and the import fails:
```
2024-11-04 12:40:54,899:API_operations.helpers.JobService:INFO Creating job 128305
2024-11-04 12:40:55,325:API_operations.imports.Import:INFO Previously loaded files: ['ecotaxa_CPICS_20240905_000023_20240905_235921.tsv', 'export_11666_20240221_1016/export_11666_20240221_1016/ecotaxa_export_11666_20240221_1016.tsv', 'ecotaxa_export.tsv', 'ecotaxa_CPICS_20240906_070000_20240906_075933.tsv', 'ecotaxa_CPICS_20240905_030003_20240905_035953.tsv']
2024-11-04 12:40:55,332:API_operations.imports.ImportBase:INFO SubTask : Unzip File into temporary folder
2024-11-04 12:40:55,399:API_operations.helpers.JobService:ERROR Unexpected termination of #128305
2024-11-04 12:40:55,399:API_operations.helpers.JobService:ERROR File is not a zip file
Traceback (most recent call last):
  File "/app/API_operations/helpers/JobService.py", line 76, in run_in_background
    self.do_background()
  File "/app/API_operations/imports/Import.py", line 81, in do_background
    self.do_validate()
  File "/app/API_operations/imports/Import.py", line 119, in do_validate
    source_dir_or_zip = self.unzip_if_needed(job_user_id)
  File "/app/API_operations/imports/ImportBase.py", line 67, in unzip_if_needed
    with zipfile.ZipFile(input_path, "r") as z:
  File "/usr/lib/python3.8/zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Please let me know if you need more details.

**Comment by grololo06** [comment]
Hello, please give it another try, copy here the details of the fresh execution  especially the job_id and I'll have a look on the server.
Thanks.

**Comment by LAMaglan** [comment]
I have tried again, with the same error when submitting the zip file with the API 
The job_id is 129750 .Server-side path from `POST: /myfiles/` is `/tmp/tmp5as36rbx.3121/ecotaxa_CPICS_20240905_000023_20240905_235921.zip`

Here is what the Ecotaxa log file is showing:
```
2024-11-18 07:26:18,388:API_operations.helpers.JobService:INFO Creating job 129750
2024-11-18 07:26:18,502:API_operations.imports.Import:INFO Previously loaded files: ['ecotaxa_CPICS_20240905_030003_20240905_035953.tsv', 'ecotaxa_export.tsv', 'ecotaxa_CPICS_20240905_000023_20240905_235921.tsv', 'ecotaxa_CPICS_20240906_070000_20240906_075933.tsv', 'export_11666_20240221_1016/export_11666_20240221_1016/ecotaxa_export_11666_20240221_1016.tsv']
2024-11-18 07:26:18,510:API_operations.imports.ImportBase:INFO SubTask : Unzip File into temporary folder
2024-11-18 07:26:18,522:API_operations.helpers.JobService:ERROR Unexpected termination of #129750
2024-11-18 07:26:18,523:API_operations.helpers.JobService:ERROR File is not a zip file
Traceback (most recent call last):
  File "/app/API_operations/helpers/JobService.py", line 76, in run_in_background
    self.do_background()
  File "/app/API_operations/imports/Import.py", line 81, in do_background
    self.do_validate()
  File "/app/API_operations/imports/Import.py", line 119, in do_validate
    source_dir_or_zip = self.unzip_if_needed(job_user_id)
  File "/app/API_operations/imports/ImportBase.py", line 66, in unzip_if_needed
    with zipfile.ZipFile(input_path, "r") as z:
  File "/usr/lib/python3.8/zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
For reference, the job_id when I upload the same zip file in the GUI, which works (and is successful) is 129751
And here is the server_side path: `/tmp/tmpmwkzuyj0.3121/ecotaxa_CPICS_20240905_000023_20240905_235921.zip`


If relevant, the task ID (129753) of a successful job, using the API with a smaller zip file (different data).
The server_side path: `/tmp/tmprzmiv16q.3121/ecotaxa_NearshoreDynamics_2024-11-15T08_32_23.286403_NearshoreDynamics_1.zip`

**Comment by grololo06** [comment]
Hello, we have server side:
```
www-data@a00240557eee:/tmp/tmp5as36rbx.3121$ ls -als
total 8
4 drwx------ 2 www-data www-data 4096 Nov 18 07:26 .
0 -rw-r--r-- 1 www-data www-data    0 Nov 18 07:26 ecotaxa_CPICS_20240905_000023_20240905_235921.zip
```
We have this line in nginx.log:
`[18/Nov/2024:07:26:16 +0000] "POST /api/my_files/ HTTP/1.1" 499 0 "-" "python-requests/2.32.3"`
The status 499 is an error condition https://stackoverflow.com/questions/12973304/possible-reason-for-nginx-499-error-codes 
Did you receive any error in your client program? Is the program shared somewhere? 
Thanks.

**Comment by LAMaglan** [comment]
The program is not shared anywhere (yet), and my client program does not throw any error. I will investigate, and then update you.
Thanks

**Comment by LAMaglan** [comment]
I have increased the timeout for the request to `POST: /myfiles/` for larger files (> 100 MB), and also for `POST: /file_import/{project_id}` (not sure if the latter is relevant). This has fixed the problem.
If you want to check, the job_id is 129759, and the server_side path is `/tmp/tmpdj5h6msq.3121/ecotaxa_CPICS_20240905_000023_20240905_235921.zip`
Thanks for the help. This issue can be closed
